name: "⚙️ infra"

on:
  push:
    branches:
      - test/deploy-infra
    paths:
      - "back-end/services/infra/**"

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=sa-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      - name: Terraform init
        run: terraform -chdir=back-end/services/infra init

      - name: Terraform plan
        run: terraform -chdir=back-end/services/infra plan

      - name: Terraform apply
        run: terraform -chdir=back-end/services/infra apply -auto-approve

      - name: Clean up
        run: rm tfplan