name: "⚙️ infra"

on:
  push:
    branches:
      - test/deploy-infra
    paths:
      - "back-end/services/infra/**"

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: aws

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: sa-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform init
        run: terraform -chdir=back-end/services/infra init

      - name: Plan Terraform changes
        run: terraform -chdir=back-end/services/infra plan -out=tfplan

      - name: Apply Terraform Changes
        run: terraform -chdir=back-end/services/infra apply -auto-approve

      - name: Clean up
        run: rm back-end/services/infra/tfplan
